/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lin_jnicppdemo_NativeFunc */

#ifndef _Included_com_lin_jnicppdemo_NativeFunc
#define _Included_com_lin_jnicppdemo_NativeFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lin_jnicppdemo_NativeFunc
 * Method:    native_init
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_lin_jnicppdemo_NativeFunc_native_1init
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
